spring:
  datasource:

    url: ${DB_URL:jdbc:postgresql://ep-wispy-wind-az0pqand-pooler.c-3.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require}
    username: ${DB_USERNAME:neondb_owner}
    password: ${DB_PASSWORD:npg_BeEZX7syJdK6}
    driver-class-name: org.postgresql.Driver

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: dev-client-id
            client-secret: dev-client-secret

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  data:
    redis:
      host: localhost
      port: 6379

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

logging:
  level:
    com.tiesverse: DEBUG
    org.springframework.security: DEBUG
